### ISSUE TITLE
解凍したファイルにPLATEAU-SDK-for-Unreal.uprojectがありません

### ISSUE THREAD

**Issue by su3free** [Synesthesias/PLATEAU-SDK-for-Unreal#44]
マニュアルに
Plugins/PLATEAU-SDK-for-Unreal/PLATEAU-SDK-for-Unreal.uprojectが存在することを確認
とありますが、解凍したファイルに該当ファイルがありません。

**Comment by dazzhe** [comment]
@su3free 
報告ありがとうございます。
マニュアルが間違っておりましたので修正いたしました。
