### ISSUE TITLE
PLATEAU could not be complied. Try rebuilding from source manually.

### ISSUE THREAD

**Issue by 2panman** [Synesthesias/PLATEAU-SDK-for-Unreal#52]
プロジェクトファイルを起動しようとすると、「PLATEAU could not be complied. Try rebuilding from source manually.」というエラー画面が出てきます。
対処法はありますでしょうか。

**Comment by FuCrowRabbit** [comment]
`Saved/Logs/`にlogファイルが生成されているはずなので、それを読めば理由が書いてあると思います。
例えばPCに、.NET Framework SDK（4.6.0以上）がインストールされていないとか･･･

**Comment by alphaizm** [comment]
私も同様な問題が出ています。
FuCrowRabbitさんの情報ありましたとおり、
logファイルを確認してみました。

以下のようなエラーの記載を確認しました。

> LogWindows: Failed to load 'aqProf.dll' (GetLastError=0)
> LogWindows: File 'aqProf.dll' does not exist
> LogProfilingDebugging: Loading WinPixEventRuntime.dll for PIX profiling (from ../../../Engine/Binaries/ThirdParty/Windows/WinPixEventRuntime/x64).
> LogWindows: Failed to load 'VtuneApi.dll' (GetLastError=0)
> LogWindows: File 'VtuneApi.dll' does not exist
> LogWindows: Failed to load 'VtuneApi32e.dll' (GetLastError=0)
> LogWindows: File 'VtuneApi32e.dll' does not exist
> LogWindows: Started CrashReportClient (pid=6316)
> LogWindows: Custom abort handler registered for crash reporting.

エラーで検索した結果、以下の通り
https://forums.unrealengine.com/t/call-unknown-function-error-aqprof-dll-related-and-selffixed/417307

> C:/Users/{system username}/AppData/Local/UnrealEngine

上記を削除して、再度シェーダーを再生成してみたんですが、
現象は改善されず・・・

他に情報があれば、教えて頂きたいです。

**Comment by dazzhe** [comment]
@2panman @alphaizm 
返信遅くなり申し訳ございません。

https://github.com/Project-PLATEAU/PLATEAU-SDK-for-Unreal/releases
v1.0.2以降ではリリースページにビルド済みパッケージを含めておりますので、こちらをご利用お願いいたします。

**Comment by alphaizm** [comment]
@dazzhe 

ご連絡ありがとうございます。
試してみたいと思います。
