### ISSUE TITLE
Get Attribute Mapが使用できない

### ISSUE THREAD

**Issue by yeczrtu** [Synesthesias/PLATEAU-SDK-for-Unreal#69]
Blueprint'/PLATEAU-SDK-for-Unreal/GetObjectInfo.GetObjectInfo'
上記のBPを開くと添付画像のコンパイルエラーが表示される

使用バージョン：PLATEAU-SDK-for-Unreal-v1.0.2
![image](https://user-images.githubusercontent.com/48671628/230049477-b63efbb7-55f3-41cd-998d-f6fdee67f95b.png)

**Comment by yeczrtu** [comment]
サンプルプロジェクトでは問題なく動作していたので、そちらのプラグインを使用しています。
https://github.com/Project-PLATEAU/PLATEAU-SDK-for-Unreal

**Comment by yeczrtu** [comment]
サンプルプロジェクト
![image](https://user-images.githubusercontent.com/48671628/230051291-9d502e3b-7b7e-4931-877a-bf2aa946ce21.png)

**Comment by yeczrtu** [comment]
#75

**Comment by dazzhe** [comment]
@yeczrtu 
ご報告ありがとうございます。
コメントいただいてますが、こちら#75 のPRで修正いたしましたのでcloseさせていただきます。
