### ISSUE TITLE
シッピングビルドが通らない

### ISSUE THREAD

**Issue by hyaguchi947d** [Synesthesias/PLATEAU-SDK-for-Unreal#70]
Project-PLATEAUブランチを使用していますが、こちらへの報告でよろしいでしょうか？

v1.0.2リリースを使用してシッピングビルドを行おうとしましたが、
いくつかエラーが発生しました。
こちらの手元で修正を行い、エディタ、シッピングともにビルドと動作を確認しましたが、
Unreal Engineの作法に不慣れなため間違いがありましたらご指摘ください。

検証した環境は以下のとおりです。
- Windows 10 Pro 22H2
- Unreal Engine 5.0.3
- Visual Studio 2022 17.5.4

こちらで修正した内容は以下のとおりです。

C4530エラー(try-catchがコンパイルできない)

`Source/PLATEAURuntime/PLATEAURuntime.Build.cs`に以下の行を追加しました。

```
bEnableExceptions = true;
```

`IDetailsView`が定義されていない

`Source/PLATEAUEditor/Private/PLATEAUExportPanel.h`
に以下を追加しました。

```
#include "Editor/PropertyEditor/Public/IDetailsView.h"
```

`UStaticMesh::GetMeshDescription()`がみつからない。

`Source/PLATEAURuntime/Private/PLATEAUMeshExporter.cpp`の130行目
`FPLATEAUMeshExporter::CreateMesh`の中で同関数を呼び出していますが、
シッピングビルドでは関数が見つかりません。

これはUE本体側のヘッダを確認したところ、

```
#if WITH_EDITORONLY_DATA
```

というフラグがたっていないと定義されないことがわかりました。
関数の中身を確認しましたが、エディタでのみ使うものと判断し
このフラグで関数の内容全体を切り替えることでコンパイルが通りました。

GetObjectInfoのエラー

以下のissueで報告されている内容と同じです。
https://github.com/Synesthesias/PLATEAU-SDK-for-Unreal/issues/69

**Comment by dazzhe** [comment]
@hyaguchi947d 
ご報告ありがとうございます。報告こちらにいただく形で問題ございません。

コンパイルエラーの修正、属性情報へのアクセスでのエラー修正[v1.1.0のリリース](https://github.com/Project-PLATEAU/PLATEAU-SDK-for-Unreal/releases/tag/v1.1.0)で対応いたしましたので、こちらでご確認いただけますでしょうか。

**Comment by linoal** [comment]
修正済みのためcloseさせていただきます。
